on:
  push:
    branches:
    - main
jobs:
  demo:
    name: Demo
    runs-on: ubuntu-latest
    steps:
      - name: toto
        run: echo "Hello World"
      - run: ls -la 
      - name: recup du code
        uses: actions/checkout@v3.5.2
      - name: test
        run: npm run test
  
  
    
      
